import React, {useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Clapperboard,FolderOpen,Save,Film,Music,Plus,Trash2,ChevronLeft,ChevronRight,Play,Pause,Download,Type,Scissors,CheckCircle2,ZoomIn,ZoomOut,GripVertical} from 'lucide-react';
import './style.css';

type Clip={path:string;url:string;name:string;duration:number;start:number;end:number;speed:number;id:string;thumbnail?:string};
type MusicFile={path:string;url:string;name:string}|null;
type Title={id:string;text:string;start:number;end:number;size:number};
type Project={clips:Clip[];music:MusicFile;texts:Title[]};
declare global {interface Window {editor:{chooseVideos:()=>Promise<Omit<Clip,'start'|'end'|'speed'|'id'>[]>;chooseAudio:()=>Promise<MusicFile>;saveProject:(p:Project)=>Promise<string|null>;openProject:()=>Promise<Project|null>;exportVideo:(p:Project)=>Promise<string|null>;makeProxy:(path:string)=>Promise<{path:string;url:string}>;onProgress:(f:(text:string)=>void)=>()=>void}}}
const uid=()=>globalThis.crypto.randomUUID();
const seconds=(s:number)=>{const n=Math.max(0,Math.floor(s));return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
const length=(c:Clip)=>(c.end-c.start)/c.speed;
function App(){
 const [clips,setClips]=useState<Clip[]>([]),[music,setMusic]=useState<MusicFile>(null),[texts,setTexts]=useState<Title[]>([]);
 const [mediaError,setMediaError]=useState(''); const [zoom,setZoom]=useState(20),[dragging,setDragging]=useState<string|null>(null); const [selected,setSelected]=useState<string|null>(null),[playhead,setPlayhead]=useState(0),[playing,setPlaying]=useState(false),[status,setStatus]=useState('Pronto para começar'),[exporting,setExporting]=useState(false);
 const vid=useRef<HTMLVideoElement>(null);const playheadRef=useRef(0); const playingRef=useRef(false); const currentRef=useRef<{clip:Clip;offset:number;local:number}|null>(null);const total=useMemo(()=>clips.reduce((x,c)=>x+length(c),0),[clips]);
 const current=useMemo(()=>{let offset=0;for(const clip of clips){const end=offset+length(clip);if(playhead<end || (clip===clips[clips.length-1]&&playhead<=end))return {clip,offset,local:Math.max(0,playhead-offset)};offset=end;}return null},[clips,playhead]);
 const selectedClip=clips.find(c=>c.id===selected)||null;
 // Prévia leve (proxy 540p, GOP curto) gerada pelo FFmpeg; a exportação continua usando os arquivos originais.
 const [proxies,setProxies]=useState<Record<string,{state:'pending'|'ready'|'failed';url?:string}>>({});const proxyAsked=useRef(new Set<string>());const totalRef=useRef(0);
 const proxyList=Object.values(proxies),proxyPending=proxyList.filter(p=>p.state==='pending').length,proxyDone=proxyList.length-proxyPending;
 const previewUrl=current?(proxies[current.clip.path]?.state==='ready'?proxies[current.clip.path].url!:current.clip.url):'';
 const viewKey=current?current.clip.id+'|'+previewUrl:'';
 const activeTitles=texts.filter(t=>playhead>=t.start&&playhead<=t.end);
 useEffect(()=>window.editor.onProgress(setStatus),[]);
 useEffect(()=>{playheadRef.current=playhead;currentRef.current=current;playingRef.current=playing;totalRef.current=total;},[playhead,current,playing,total]);
 // A troca de clipe exige novo src; atualizações normais do contador não devem buscar o vídeo a cada frame.
 useEffect(()=>{const v=vid.current;if(!v||!current)return;setMediaError('');v.playbackRate=current.clip.speed;const target=current.clip.start+current.local*current.clip.speed;const seek=()=>{if(Number.isFinite(v.duration)&&Math.abs(v.currentTime-target)>0.15)v.currentTime=target;if(playingRef.current)v.play().catch(e=>{if(e.name!=='AbortError')setMediaError('Não foi possível iniciar a reprodução: '+e.message)});};if(v.readyState>=1)seek();else v.addEventListener('loadedmetadata',seek,{once:true});return()=>v.removeEventListener('loadedmetadata',seek);},[viewKey]);
 useEffect(()=>{const v=vid.current;if(!v||!current)return;v.playbackRate=current.clip.speed;if(playing)v.play().catch(e=>{if(e.name!=='AbortError')setMediaError('Erro ao reproduzir: '+e.message)});else v.pause();},[playing,viewKey,current?.clip.speed]);
 useEffect(()=>{const v=vid.current;if(!v||!current||playing)return;const target=current.clip.start+current.local*current.clip.speed;if(v.readyState>=1&&Math.abs(v.currentTime-target)>0.12)v.currentTime=target;},[playhead,playing,viewKey]);
 useEffect(()=>{if(playing&&playhead>=total){setPlaying(false)}},[playhead,total,playing]);
 // Relógio da reprodução: detecta o fim do corte a cada quadro (o evento timeupdate só dispara ~4x/s e deixava passar até 250 ms
 // do trecho seguinte) e atualiza a interface no máximo ~20x/s para não re-renderizar o app inteiro sem necessidade.
 useEffect(()=>{if(!playing)return;let raf=0,last=0,pause=0;
  const tick=(now:number)=>{raf=requestAnimationFrame(tick);
   const v=vid.current,cur=currentRef.current;if(!v||!cur||v.seeking||v.readyState<2||now<pause)return;
   const total=totalRef.current,clipEnd=cur.offset+length(cur.clip),at=cur.offset+Math.max(0,(v.currentTime-cur.clip.start)/cur.clip.speed);
   if(at>=clipEnd-0.03){pause=now+150;last=now;if(clipEnd>=total-0.05){setPlaying(false);setPlayhead(total)}else setPlayhead(clipEnd+0.01);return}
   if(now-last>=50){last=now;setPlayhead(Math.min(total,at))}};
  raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[playing]);
 function ensureProxies(paths:string[]){for(const path of new Set(paths)){if(proxyAsked.current.has(path))continue;proxyAsked.current.add(path);setPlaying(false);
   setProxies(a=>({...a,[path]:{state:'pending'}}));
   window.editor.makeProxy(path).then(r=>setProxies(a=>({...a,[path]:{state:'ready',url:r.url}}))).catch(e=>{console.error(e);setStatus('Não foi possível otimizar a prévia de um vídeo; será usado o arquivo original.');setProxies(a=>({...a,[path]:{state:'failed'}}))})}}
 async function importClips(){try{const input=await window.editor.chooseVideos();const more=input.map(c=>({...c,start:0,end:c.duration,speed:1,id:uid()}));setClips(a=>[...a,...more]);ensureProxies(more.map(c=>c.path));if(more.length&&!selected)setSelected(more[0].id);setStatus(`${more.length} vídeo(s) importado(s).`)}catch(e){alert(String(e))}}
 async function importMusic(){try{const f=await window.editor.chooseAudio();if(f)setMusic(f)}catch(e){alert(String(e))}}
 function changeClip(change:Partial<Clip>){if(!selected)return;setClips(a=>a.map(c=>c.id===selected?{...c,...change}:c));setPlaying(false);setPlayhead(0)}
 function reorder(fromId:string,toId:string){if(fromId===toId)return;setClips(old=>{const result=[...old];const from=result.findIndex(x=>x.id===fromId),to=result.findIndex(x=>x.id===toId);if(from<0||to<0)return old;const [item]=result.splice(from,1);result.splice(to,0,item);return result});setPlaying(false);setPlayhead(0)}
 function splitAtPlayhead(){const c=current?.clip;if(!c)return;const sourceTime=c.start+current!.local*c.speed;if(sourceTime<=c.start+0.1||sourceTime>=c.end-0.1){setStatus('Posicione a cabeça de reprodução dentro do clipe.');return}const second={...c,id:uid(),start:sourceTime};setClips(old=>old.flatMap(x=>x.id===c.id?[{...x,end:sourceTime},second]:[x]));setSelected(second.id);setPlaying(false);setStatus('Clipe dividido em dois.');}
 function move(index:number,d:number){const next=[...clips],to=index+d;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];setClips(next);setPlayhead(0);setPlaying(false)}
 const project=():Project=>({clips,music,texts});
 async function save(){try{const p=await window.editor.saveProject(project());if(p)setStatus('Projeto salvo: '+p)}catch(e){alert(String(e))}}
 async function open(){try{const p=await window.editor.openProject();if(!p)return;setClips(p.clips.map(c=>({...c,id:c.id||uid()})));ensureProxies(p.clips.map(c=>c.path));setMusic(p.music);setTexts((p.texts||[]).map(t=>({...t,id:t.id||uid()})));setSelected(p.clips[0]?.id||null);setPlayhead(0);setPlaying(false);setStatus('Projeto aberto.')}catch(e){alert(String(e))}}
 async function exportMovie(){if(!clips.length)return;setPlaying(false);setExporting(true);try{const p=await window.editor.exportVideo(project());if(p)setStatus('Exportado: '+p);else setStatus('Exportação cancelada.')}catch(e){setStatus('Erro na exportação');alert(String(e))}finally{setExporting(false)}}
 return <div className="app">
  <header><div className="brand"><Clapperboard size={25}/><div><strong>EDEN <span>VIDEO EDITOR</span></strong><small>Studio • v0.2.2</small></div></div><div className="toolbar"><button onClick={open}><FolderOpen size={17}/> Abrir projeto</button><button onClick={save}><Save size={17}/> Salvar</button><button className="primary" onClick={exportMovie} disabled={!clips.length||exporting}><Download size={17}/>{exporting?'Exportando...':'Exportar MP4'}</button></div></header>
  <section className="workspace">
   <aside className="library"><div className="section-title"><Film size={17}/> Biblioteca</div><button className="add" onClick={importClips}><Plus size={17}/> Importar vídeos</button><button className="add secondary" onClick={importMusic}><Music size={17}/> Adicionar música</button><div className="library-items">{clips.map((c,i)=><div key={c.id} className={'asset '+(selected===c.id?'chosen':'')} onClick={()=>setSelected(c.id)}><Film size={18}/><span title={c.path}>{i+1}. {c.name}<small>{seconds(c.duration)}</small></span></div>)}{music&&<div className="asset music"><Music size={18}/><span title={music.path}>{music.name}<small>Trilha de fundo</small></span><button title="Remover música" onClick={()=>setMusic(null)}><Trash2 size={14}/></button></div>}{!clips.length&&<p className="hint">Importe arquivos para montar sua primeira sequência.</p>}</div></aside>
   <main className="center"><div className="section-title">Pré-visualização <span>1280 × 720 • 16:9</span></div><div className="preview-shell"><div className="preview">{current?<><video key={viewKey} ref={vid} src={previewUrl} preload="auto" onError={e=>{const v=e.currentTarget;setMediaError('Falha na leitura do arquivo (código '+(v.error?.code||'?')+'). Verifique o formato e tente novamente.');setPlaying(false)}} onEnded={()=>{if(current.offset+length(current.clip)<total)setPlayhead(current.offset+length(current.clip)+0.001);else {setPlaying(false);setPlayhead(total)}}} playsInline/><div className="titles">{activeTitles.map(t=><div key={t.id} style={{fontSize:`${Math.min(44,t.size*.75)}px`}}>{t.text}</div>)}</div>{proxyPending>0&&<div className="optimizing"><strong>Otimizando a prévia para reprodução fluida…</strong><span>{proxyDone} de {proxyList.length} vídeos prontos • a exportação usa a qualidade original</span></div>}</>:<div className="empty"><Clapperboard size={48}/><h2>Seu próximo vídeo começa aqui</h2><p>Importe clipes para visualizar a edição.</p></div>}</div></div><div className="transport"><button disabled={!clips.length} onClick={()=>{setPlaying(false);setPlayhead(0)}}><ChevronLeft size={18}/></button><button className="play" disabled={!clips.length||proxyPending>0} title={proxyPending>0?'Aguarde a otimização da prévia':'Reproduzir / pausar'} onClick={()=>{if(playhead>=total){setPlayhead(0);setPlaying(true)}else setPlaying(!playing)}}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><button disabled={!clips.length} onClick={()=>{setPlaying(false);setPlayhead(total)}}><ChevronRight size={18}/></button><strong>{seconds(playhead)} <span>/ {seconds(total)}</span></strong></div></main>
   <aside className="inspector"><div className="section-title"><Scissors size={17}/> Propriedades</div>{selectedClip?<div className="fields"><label>Vídeo selecionado<strong title={selectedClip.path}>{selectedClip.name}</strong></label><label>Início do corte (segundos)<input type="number" min="0" max={Math.max(0,selectedClip.end-0.1)} step="0.1" value={selectedClip.start} onChange={e=>{const n=Number(e.target.value);if(n>=0&&n<selectedClip.end)changeClip({start:n})}}/></label><label>Fim do corte (segundos)<input type="number" min={selectedClip.start+0.1} max={selectedClip.duration} step="0.1" value={selectedClip.end} onChange={e=>{const n=Number(e.target.value);if(n>selectedClip.start&&n<=selectedClip.duration)changeClip({end:n})}}/></label><label>Velocidade<select value={selectedClip.speed} onChange={e=>changeClip({speed:Number(e.target.value)})}>{[0.25,0.5,0.75,1,1.25,1.5,2,3,4].map(x=><option key={x} value={x}>{x}×</option>)}</select><input aria-label="Velocidade personalizada" type="number" min="0.25" max="4" step="0.05" value={selectedClip.speed} onChange={e=>{const n=Number(e.target.value);if(n>=0.25&&n<=4)changeClip({speed:n})}}/></label><div className="notice">Duração na sequência: {seconds(length(selectedClip))}</div><button className="danger" onClick={()=>{setClips(a=>a.filter(c=>c.id!==selected));setSelected(null);setPlaying(false);setPlayhead(0)}}><Trash2 size={16}/> Remover clipe</button></div>:<p className="hint">Selecione um clipe para editar seus cortes e velocidade.</p>}
   <div className="divider"/><div className="section-title"><Type size={17}/> Textos</div><button className="add" onClick={()=>setTexts(t=>[...t,{id:uid(),text:'Novo título',start:Math.min(playhead,total),end:Math.min(total,playhead+4)>playhead?Math.min(total,playhead+4):playhead+4,size:40}])} disabled={!clips.length}><Plus size={16}/> Inserir texto</button><div className="text-items">{texts.map(t=><div className="text-edit" key={t.id}><input aria-label="Texto" value={t.text} maxLength={180} onChange={e=>setTexts(a=>a.map(x=>x.id===t.id?{...x,text:e.target.value}:x))}/><div className="two"><label>Início<input type="number" min="0" step="0.1" value={t.start} onChange={e=>setTexts(a=>a.map(x=>x.id===t.id?{...x,start:Number(e.target.value)}:x))}/></label><label>Fim<input type="number" min="0" step="0.1" value={t.end} onChange={e=>setTexts(a=>a.map(x=>x.id===t.id?{...x,end:Number(e.target.value)}:x))}/></label></div><div className="two"><label>Tamanho<input type="number" min="12" max="100" value={t.size} onChange={e=>setTexts(a=>a.map(x=>x.id===t.id?{...x,size:Number(e.target.value)}:x))}/></label><button onClick={()=>setTexts(a=>a.filter(x=>x.id!==t.id))} title="Remover"><Trash2 size={16}/></button></div></div>)}</div></aside>
  </section>
  <section className="timeline"><div className="timeline-head"><div className="section-title">Linha do tempo <span>Arraste clipes para reorganizar • arraste a régua para navegar</span></div><div className="timeline-tools"><button title="Dividir no cursor" onClick={splitAtPlayhead} disabled={!current}><Scissors size={15}/> Dividir</button><button onClick={()=>setZoom(z=>Math.max(8,z-5))} title="Reduzir zoom"><ZoomOut size={15}/></button><span>{zoom}px/s</span><button onClick={()=>setZoom(z=>Math.min(100,z+5))} title="Ampliar zoom"><ZoomIn size={15}/></button></div></div>
   <div className="timeline-scroll"><div className="timeline-body" style={{width:`max(100%, ${Math.max(1,total)*zoom+100}px)`}}><div className="ruler"><div className="tracklabel">TEMPO</div><div className="ruler-scale" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setPlaying(false);setPlayhead(Math.max(0,Math.min(total,(e.clientX-r.left)/zoom)))}}>{Array.from({length:Math.floor(total/5)+1},(_,i)=><span key={i} style={{left:`${i*5*zoom}px`}}>{seconds(i*5)}</span>)}<div className="ruler-cursor" style={{left:`${playhead*zoom}px`}}/></div></div>
   <div className="track"><div className="tracklabel"><Film size={15}/> VÍDEO</div><div className="trackclips">{clips.map((c,i)=><div key={c.id} className={'segment '+(selected===c.id?'active':'')} draggable onDragStart={e=>{setDragging(c.id);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',c.id)}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();reorder(e.dataTransfer.getData('text/plain')||dragging||'',c.id);setDragging(null)}} onDragEnd={()=>setDragging(null)} style={{width:`${Math.max(32,length(c)*zoom)}px`,backgroundImage:c.thumbnail?`linear-gradient(0deg,#0c2339ee,#10263d55),url("${c.thumbnail}")`:undefined}} onClick={()=>{setSelected(c.id);setPlaying(false);setPlayhead(clips.slice(0,i).reduce((v,x)=>v+length(x),0))}}><GripVertical size={15}/><span>{i+1}. {c.name}</span><small>{seconds(length(c))} • {c.speed}×</small></div>)}</div></div><div className="track audio"><div className="tracklabel"><Music size={15}/> ÁUDIO</div><div className="musictrack" style={{width:`${Math.max(total*zoom,200)}px`}}>{music?<><Music size={15}/>{music.name} <span>música de fundo</span></>:<span>Nenhuma música adicionada</span>}</div></div><div className="track titletrack"><div className="tracklabel"><Type size={15}/> TEXTOS</div><div className="texttrack" style={{width:`${Math.max(total*zoom,200)}px`}}>{texts.map(x=><span key={x.id} className="title-segment" style={{left:x.start*zoom,width:Math.max(30,(x.end-x.start)*zoom)}} title={`${seconds(x.start)} a ${seconds(x.end)}`}>{x.text}</span>)}{!texts.length&&'Nenhum texto adicionado'}</div></div></div></div></section>
  <footer><span><CheckCircle2 size={14}/> {status}</span><span>Processamento local • seus arquivos permanecem no computador</span></footer>
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
